### ISSUE TITLE
setup react-query or redux-toolkit-query 

### ISSUE THREAD

**Issue by coofzilla** [joemcgee4151986/mmafighterstats#4]
up to you which you use. I don't think this app will need redux, I'd lean towards react-query unless u simply want to use redux to learn it.

**Comment by joemcgee4151986** [comment]
I'm more of a simple guy. I'm totally new to this so if you're leaning towards react-query, I'll do it. I trust your judgement.

**Comment by joemcgee4151986** [comment]
installed react-query
